name = "spawn"
description = "A simple library to spawn processes and communicate with them."
long-description = "This is Glib indepentent implementation of a spawn processes interface."
version = "23.0.0-git"
website = "https://github.com/reznikmm/spawn"
authors = ["AdaCore", "Max Reznik"]
licenses = "Apache-2.0"
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["gnat/spawn.gpr"]
tags = ["process", "launch", "pipe"]

[configuration]
generate_ada = false
generate_c = false

[build-switches]
"*".ada_version = "Ada2022"

[gpr-externals]
OS = ["unix", "osx", "Windows_NT"]

[gpr-set-externals.'case(os)']
linux   = { OS = "unix" } # Compact table syntax is convenient in this case
windows = { OS = "Windows_NT" }  # to see all enumeration values, one per row.
macos   = { OS = "osx" }

