------------------------------------------------------------------------------
--                         Language Server Protocol                         --
--                                                                          --
--                     Copyright (C) 2018-2021, AdaCore                     --
--                                                                          --
-- This is free software;  you can redistribute it  and/or modify it  under --
-- terms of the  GNU General Public License as published  by the Free Soft- --
-- ware  Foundation;  either version 3,  or (at your option) any later ver- --
-- sion.  This software is distributed in the hope  that it will be useful, --
-- but WITHOUT ANY WARRANTY;  without even the implied warranty of MERCHAN- --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public --
-- License for  more details.  You should have  received  a copy of the GNU --
-- General  Public  License  distributed  with  this  software;   see  file --
-- COPYING3.  If not, go to http://www.gnu.org/licenses for a complete copy --
-- of the license.                                                          --
--                                                                          --
-- As a special exception under Section 7 of GPL version 3, you are granted --
-- additional permissions described in the GCC Runtime Library Exception,   --
-- version 3.1, as published by the Free Software Foundation.               --
------------------------------------------------------------------------------

procedure Spawn.Processes.Monitor_Loop (Timeout : Integer);
--  Drive process control engine, deliver events, watch child processes, etc.
--
--  Timeout to run in milliseconds. Don't wait if zero. Wait forever if < 0.
--  If there are some events then procedure will return before timeout
--  expires.
--
--  Note: This procedure is NOT thread-safe! In multi-tasking environment
--  create a dedicated task to drive the engine.
--
--  In single task application you should call this to drive process engine.
--
--  In Glib enabled application the engine is integrated it the Glib event
--  loop and this procedure shouldn't be used.
